#!/bin/bash
#
# Copyright © 2024 Joshua Rose
# 
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

. bin/defs.sh
. bin/util.sh
. bin/check/font_installed.sh
. bin/check/online.sh
. bin/check/root.sh
. bin/install/astro.sh
. bin/install/bash.sh
. bin/install/font.sh
. bin/install/package.sh
. bin/install/rust.sh
. bin/install/treesitter.sh
. bin/install/vim.sh
. bin/install/zsh.sh

# cleanup unneeded files if installed previously
rm -fr $HOME/tmp
rm -fr /tmp/vim
rm -fr /tmp/aliases
rm -fr /tmp/bashrc
rm -fr /tmp/packages
rm -fr /tmp/rustup

check_online
check_not_root $USER

sudo apt update

# ADD ANY OTHER PACKAGES YOU WISH TO INSTALL HERE
install_packages "git" "curl" "wget" "fzf" "gpg"

# Choose one or more of the following fonts:
install_fonts "NerdFontsSymbolsOnly.zip" "FiraCode.zip" "FiraMono.zip" "Agave.zip" "DroidSansMono.zip" "FantasqueSansMono.zip"


if [ -L $PATH_USER_BINARIES/zsh ] || [ -L $HOME/.zshrc ]; then
  read -p "Existing zsh installation found. Would you like to overwrite it? (y/*N) " -n 1 -r REPLY
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo 
    [ -L $HOME/.zsh_history ] && rm $HOME/.zsh_history
    [ -L $HOME/.zshrc ] && rm $HOME/.zshrc
    [ -d $HOME/.oh-my-zsh/ ] && rm -rf $HOME/.oh-my-zsh/

    install_zsh > /dev/null &
    spinner $! "Installing zsh"

    # once zsh is installed, remove the installatino
    # set by omz and replace it with a custom one.
    [ -L $HOME/.zshrc ] && rm $HOME/.zshrc
    ln -s src/zsh/.zshrc $HOME/.zshrc
    source src/zsh/.zshrc
  fi
else
  read -p "Would you like to install zsh? (*Y/n) " -n 1 -r REPLY
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo 
    [ -L $HOME/.zsh_history ] && rm $HOME/.zsh_history
    [ -d $HOME/.oh-my-zsh/ ] && rm -rf $HOME/.oh-my-zsh/

    install_zsh > /dev/null &
    spinner $! "Installing zsh"

    # once zsh is installed, remove the installatino
    # set by omz and replace it with a custom one.
    [ -L $HOME/.zshrc ] && rm $HOME/.zshrc
    ln -s src/zsh/.zshrc $HOME/.zshrc
  else
    if [ ! -L $HOME/.bashrc ]; then
      install_bash
      [ -L $HOME/aliases ] && rm $HOME/aliases
      ln -s src/bash/aliases $HOME/aliases
      ln -s src/bash/bashrc $HOME/.bashrc
    fi
  fi
fi

if [ -L "$PATH_USER_BINARIES/vim" ]; then
  read -p "Existing vim installation found. Would you like to overwrite it? (y/*N) " -n 1 -r REPLY
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo 
    install_vim
    [ -d $HOME/.vim ] && rm -rf $HOME/.vim
    [ -L $HOME/.vimrc ] && rm -rf $HOME/.vimrc
    ln -s src/vim/.vim/ $HOME/.vim
    ln -s src/vim/.vimrc $HOME/.vimrc
  fi
else
  read -p "Would you like to install vim? (*Y/n) " -n 1 -r REPLY
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo 
    install_vim
    ln -s src/vim/.vim/ $HOME/.vim
    ln -s src/vim/.vimrc $HOME/.vimrc
  fi
fi

if [ -L "$PATH_USER_BINARIES/nvim" ]; then
  read -p "Existing neovim installation found. Would you like to overwrite it? (y/*N) " -n 1 -r REPLY
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo 
    rm -rf $HOME/.config/nvim
    install_astro
  fi
else
  read -p "Would you like to install astronvim? (*Y/n) " -n 1 -r REPLY
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo 
    install_astro
  fi
fi

if [ ! -d "$HOME/.rustup" ]; then
  read -p "Would you like to install Rust? (*Y/n) " -n 1 -r REPLY
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo 
    install_rust
  fi
fi

if [ ! -x "$(command -v eza)" ]; then
  read -p "Would you like to install eza (ls alternative)? (*Y/n) " -n 1 -r REPLY
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo 
    . bin/install/eza.sh
  fi
fi

if [ -x "$(command -v tmux)" ]; then
  read -p "Existing tmux installation found. Would you like to overwrite it? (y/*N) " -n 1 -r REPLY
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo 
    mkdir -p ~/.tmux/plugins ~/.config/tmux
    install_packages "tmux"

    read -p "Would you like to install a pre-populated tmux config file?" -n 1 -r REPLY
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      echo 
      # install tpm
      git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
      # link config file(s)
      [ -d "$HOME/.config/tmux" ] && rm -rf $HOME/.config/tmux
      ln -s src/tmux $HOME/.config/tmux
    else
      read -p "Would you like to install a plugin manager for tmux? (recommended)" -n 1 -r REPLY
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo 
        # install tpm
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        # add tpm to the config
        touch ~/.config/tmux/tmux.conf
        echo "set -g @plugin 'tmux-plugins/tpm'" >> ~/.config/tmux/tmux.conf
        echo "run '~/.tmux/plugins/tpm/tpm'" >> ~/.config/tmux/tmux.conf
      fi
    fi
  fi
else
  read -p "Would you like to install tmux? (*Y/n) " -n 1 -r REPLY
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo
    mkdir -p ~/.tmux/plugins ~/.config/tmux
    install_packages "tmux"

    read -p "Would you like to install a pre-populated tmux config file?" -n 1 -r REPLY
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      echo
      # install tpm
      git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
      if [ ! -L ~/.config/tmux/tmux.conf]; then
        # add tpm to the config
        touch ~/.config/tmux/tmux.conf
        echo "set -g @plugin 'tmux-plugins/tpm'" >> ~/.config/tmux/tmux.conf
        echo "run '~/.tmux/plugins/tpm/tpm'" >> ~/.config/tmux/tmux.conf
        # link config file(s)
        [ -d "$HOME/.config/tmux" ] && rm -rf $HOME/.config/tmux
        ln -s src/tmux $HOME/.config/tmux
      fi
    else
      read -p "Would you like to install a plugin manager for tmux? (recommended)" -n 1 -r REPLY
      if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo
        # install tpm
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        # add tpm to the config
        if [ ! -L ~/.config/tmux/tmux.conf]; then
          touch ~/.config/tmux/tmux.conf
          echo "set -g @plugin 'tmux-plugins/tpm'" >> ~/.config/tmux/tmux.conf
          echo "run '~/.tmux/plugins/tpm/tpm'" >> ~/.config/tmux/tmux.conf
        fi
      fi
    fi
  fi
fi

exit 0
